foo = ['a', 'b', 'c']
print(foo[3])      # will this result in an error? YES - Index out of range error